### ISSUE TITLE
Feature: hovering over an image in Google images will display the original

### ISSUE THREAD

**Issue by Saud-97** [buzamahmooza/Helpful-Web-Userscripts#1]
Can you make it in a way that you replace only the images that the mouse hover at them for half a sec or the ones that the user clicks on.
Then I believe the extension will be very fast and efficient

**Comment by buzamahmooza** [comment]
The feature (mouseover loads original images) has been added in the new version of [SuperGoogle](https://github.com/buzamahmooza/Helpful-Web-Userscripts/blob/master/SuperGoogle.user.js) in this [commit](https://github.com/buzamahmooza/Helpful-Web-Userscripts/commit/6aabd0fce11f52f993a717bf3f480f02c132490d#diff-e3adba9c7c967f88e30e419dcd5cd401).
